
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { Table } from "@heroui/react";
import TutorsModalDelete from "@/components/TutorsModalDelete";
import TutorModalUpdate from "@/components/TutorModalUpdate";

export const metadata = {
  title: "my tutors || MediQueue",
  description: "Generated by create next app",
};

const MyTutorsPage = async () => {
  const tokenData = await auth.api.getToken({
    headers: await headers(),
  });

  const res = await fetch(`${process.env.NEXT_PUBLIC_URI}/my-tutors`, {
    headers: {
      Authorization: `Bearer ${tokenData.token}`,
    },
  
  });

  const tutors = await res.json();

  console.log(tutors, "my tutors");

  return (
    <div className="container mx-auto px-4 py-10">
     

      {tutors.length === 0 ? (
        <div className="rounded-xl border border-default-200 p-10 text-center">
          <h2 className="text-xl font-semibold">No Tutors Found</h2>
          <p className="mt-2 text-default-500">
            You have not added any tutors yet.
          </p>
        </div>
      ) : (
        <Table aria-label="My tutors table">
          <Table.ScrollContainer>
            <Table.Content className="min-w-[900px]">
              <Table.Header>
                <Table.Column isRowHeader>Tutor Name</Table.Column>
                <Table.Column>Subject</Table.Column>
                <Table.Column>Available Days</Table.Column>
                <Table.Column>Hourly Fee</Table.Column>
                <Table.Column>Location</Table.Column>
                <Table.Column>Teaching Mode</Table.Column>
                <Table.Column>Actions</Table.Column>
              </Table.Header>

              <Table.Body>
                {tutors.map((tutor) => (
                  <Table.Row key={tutor._id}>
                    <Table.Cell>{tutor.tutorName}</Table.Cell>

                    <Table.Cell>{tutor.subject}</Table.Cell>

                    <Table.Cell>
                      {Array.isArray(tutor.availableDays)
                        ? tutor.availableDays.join(", ")
                        : tutor.availableDays}
                    </Table.Cell>

                    <Table.Cell>${tutor.hourlyFee}</Table.Cell>

                    <Table.Cell>{tutor.location}</Table.Cell>

                    <Table.Cell>{tutor.teachingMode}</Table.Cell>

                    <Table.Cell>
                      <div className="flex gap-2">
                    <TutorModalUpdate tutor={tutor} token ={tokenData.token}/>

                      <TutorsModalDelete tutor={tutor} token={tokenData.token}/>
                      </div>
                    </Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table.Content>
          </Table.ScrollContainer>
        </Table>
      )}
    </div>
  );
};

export default MyTutorsPage;

